# Generated by Django 5.1.5 on 2025-01-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
